"""baseline: initial MaterialHub schema

Revision ID: 2b64dcc9342a
Revises: 
Create Date: 2026-09-20 11:55:37.134278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260901_0000'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_inquiry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('company', sa.String(length=120), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_inquiry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_inquiry_email'), ['email'], unique=False)

    op.create_table('material_trace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_code', sa.String(length=80), nullable=False),
    sa.Column('item_code', sa.String(length=80), nullable=False),
    sa.Column('material_description', sa.Text(), nullable=False),
    sa.Column('heat_no', sa.String(length=80), nullable=True),
    sa.Column('lot_no', sa.String(length=80), nullable=True),
    sa.Column('serial_no', sa.String(length=80), nullable=True),
    sa.Column('batch_no', sa.String(length=80), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('po_no', sa.String(length=50), nullable=True),
    sa.Column('delivery_id', sa.String(length=50), nullable=True),
    sa.Column('warehouse_id', sa.String(length=50), nullable=True),
    sa.Column('supplier_name', sa.String(length=150), nullable=True),
    sa.Column('project_no', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_trace', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_trace_batch_no'), ['batch_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_trace_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_trace_delivery_id'), ['delivery_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_trace_heat_no'), ['heat_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_trace_item_code'), ['item_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_trace_lot_no'), ['lot_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_trace_po_no'), ['po_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_trace_project_no'), ['project_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_trace_serial_no'), ['serial_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_trace_trace_code'), ['trace_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_material_trace_warehouse_id'), ['warehouse_id'], unique=False)

    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_no', sa.String(length=50), nullable=False),
    sa.Column('project_name', sa.String(length=100), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_project_no'), ['project_no'], unique=True)

    op.create_table('schedule_risk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=80), nullable=False),
    sa.Column('material_description', sa.Text(), nullable=True),
    sa.Column('required_date', sa.Date(), nullable=True),
    sa.Column('expected_available_date', sa.Date(), nullable=True),
    sa.Column('current_stock', sa.Float(), nullable=True),
    sa.Column('required_qty', sa.Float(), nullable=True),
    sa.Column('coverage_qty', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('days_to_risk', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('project_no', sa.String(length=50), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedule_risk', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_risk_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_risk_item_code'), ['item_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_risk_project_no'), ['project_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_schedule_risk_risk_score'), ['risk_score'], unique=False)

    op.create_table('material_document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trace_id', sa.Integer(), nullable=True),
    sa.Column('document_type', sa.Enum('MTC', 'COC', 'DATASHEET', 'DRAWING', 'OTHER', name='documenttype'), nullable=False),
    sa.Column('document_no', sa.String(length=100), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('revision', sa.String(length=30), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['trace_id'], ['material_trace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_document_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_document_trace_id'), ['trace_id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('company_email', sa.String(length=120), nullable=False),
    sa.Column('company_phone', sa.String(length=20), nullable=True),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('company_address', sa.String(length=200), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('access_level', sa.Enum('project_manager', 'engineering', 'purchase', 'quality', 'delivery', 'warehouse', 'supplier', name='accesslevel'), nullable=False),
    sa.Column('store_name', sa.String(length=100), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('totp_secret', sa.String(length=32), nullable=True),
    sa.Column('qr_code_base64', sa.Text(), nullable=True),
    sa.Column('totp_confirmed', sa.Boolean(), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_company_email'), ['company_email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_project_id'), ['project_id'], unique=False)

    op.create_table('material_price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_code', sa.String(length=80), nullable=False),
    sa.Column('material_description', sa.Text(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(length=30), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_price_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_price_history_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_price_history_item_code'), ['item_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_price_history_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_price_history_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('material_requisition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mr_no', sa.String(length=50), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('drawing_no', sa.String(length=50), nullable=True),
    sa.Column('drawing_revision', sa.String(length=10), nullable=True),
    sa.Column('drawing_page', sa.String(length=10), nullable=True),
    sa.Column('material_type', sa.String(length=50), nullable=True),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('material_description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('size_inches', sa.Float(), nullable=True),
    sa.Column('thickness_mm', sa.Float(), nullable=True),
    sa.Column('length_mm', sa.Float(), nullable=True),
    sa.Column('discipline', sa.String(length=50), nullable=False),
    sa.Column('added_by', sa.String(length=100), nullable=False),
    sa.Column('edited_by', sa.String(length=100), nullable=False),
    sa.Column('required_date', sa.Date(), nullable=False),
    sa.Column('unit_of_measure', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('spare_part_quantity', sa.Float(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('standard_specification', sa.String(length=100), nullable=True),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('project_no', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='approvalstatus'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('documents', sa.Text(), nullable=True),
    sa.Column('suggested_vendor', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_requisition', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_requisition_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_requisition_item_code'), ['item_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_requisition_mr_no'), ['mr_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_material_requisition_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_requisition_project_no'), ['project_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_requisition_user_id'), ['user_id'], unique=False)

    op.create_table('purchase_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'issued', 'delivered', 'cancelled', name='purchaseorderstatus'), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=True),
    sa.Column('delivered_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_order_no'), ['order_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_purchase_order_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_user_id'), ['user_id'], unique=False)

    op.create_table('supplier_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('material_name', sa.String(length=100), nullable=False),
    sa.Column('material_type', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('available_qty', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('delivery_time_days', sa.Integer(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_material', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_material_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_material_user_id'), ['user_id'], unique=False)

    op.create_table('supplier_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('otif_score', sa.Float(), nullable=True),
    sa.Column('price_score', sa.Float(), nullable=True),
    sa.Column('responsiveness_score', sa.Float(), nullable=True),
    sa.Column('lead_time_score', sa.Float(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('orders_count', sa.Integer(), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_score', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_score_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_score_overall_score'), ['overall_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_score_period'), ['period'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_score_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('approval',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requisition_id', sa.Integer(), nullable=False),
    sa.Column('approver_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='approvalstatus'), nullable=False),
    sa.Column('approved_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['requisition_id'], ['material_requisition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approval', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_approver_id'), ['approver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_requisition_id'), ['requisition_id'], unique=False)

    op.create_table('delivery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('delivery_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('pending', 'in_transit', 'delivered', 'delayed', name='deliverystatus'), nullable=False),
    sa.Column('delivered_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_delivery_id'), ['delivery_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_delivery_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_user_id'), ['user_id'], unique=False)

    op.create_table('material_receipt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_no', sa.String(length=50), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('received_qty', sa.Float(), nullable=True),
    sa.Column('receipt_date', sa.Date(), nullable=True),
    sa.Column('accepted_qty', sa.Float(), nullable=True),
    sa.Column('rejected_qty', sa.Float(), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('material_receipt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_material_receipt_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_receipt_po_id'), ['po_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_material_receipt_receipt_no'), ['receipt_no'], unique=True)

    op.create_table('purchase_order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_order_id', sa.Integer(), nullable=False),
    sa.Column('material_requisition_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['material_requisition_id'], ['material_requisition.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_order_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_item_material_requisition_id'), ['material_requisition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_item_purchase_order_id'), ['purchase_order_id'], unique=False)

    op.create_table('quality_control',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('passed', 'failed', 'pending', name='inspectionstatus'), nullable=False),
    sa.Column('inspected_date', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quality_control', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quality_control_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_control_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_quality_control_user_id'), ['user_id'], unique=False)

    op.create_table('rfq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfq_no', sa.String(length=50), nullable=False),
    sa.Column('mr_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'quoted', 'awarded', 'closed', name='rfqstatus'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('target_quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('specification', sa.Text(), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['mr_id'], ['material_requisition.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rfq', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rfq_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_rfq_mr_id'), ['mr_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rfq_rfq_no'), ['rfq_no'], unique=True)

    op.create_table('supplier_invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_no', sa.String(length=80), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('invoice_amount', sa.Float(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'matched', 'exception', name='matchstatus'), nullable=True),
    sa.Column('variance_amount', sa.Float(), nullable=True),
    sa.Column('company_name', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('supplier_invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_invoice_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_invoice_invoice_no'), ['invoice_no'], unique=True)
        batch_op.create_index(batch_op.f('ix_supplier_invoice_po_id'), ['po_id'], unique=False)

    op.create_table('tender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_no', sa.String(length=50), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('material_requisition_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', 'cancelled', name='tenderstatus'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['material_requisition_id'], ['material_requisition.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tender', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tender_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_tender_created_by'), ['created_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_tender_material_requisition_id'), ['material_requisition_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tender_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tender_tender_no'), ['tender_no'], unique=True)

    op.create_table('bid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('bid_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='bidstatus'), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['supplier_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['tender_id'], ['tender.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bid', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bid_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_bid_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bid_tender_id'), ['tender_id'], unique=False)

    op.create_table('rfq_supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rfq_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('invited_at', sa.DateTime(), nullable=True),
    sa.Column('quoted_at', sa.DateTime(), nullable=True),
    sa.Column('quoted_price', sa.Float(), nullable=True),
    sa.Column('quoted_qty', sa.Float(), nullable=True),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('commercial_score', sa.Float(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfq.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rfq_supplier', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rfq_supplier_rfq_id'), ['rfq_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rfq_supplier_supplier_id'), ['supplier_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rfq_supplier_total_score'), ['total_score'], unique=False)

    op.create_table('three_way_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('po_id', sa.Integer(), nullable=False),
    sa.Column('receipt_id', sa.Integer(), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=True),
    sa.Column('po_amount', sa.Float(), nullable=True),
    sa.Column('receipt_amount', sa.Float(), nullable=True),
    sa.Column('invoice_amount', sa.Float(), nullable=True),
    sa.Column('variance_amount', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'matched', 'exception', name='matchstatus'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['supplier_invoice.id'], ),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_order.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['material_receipt.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('three_way_match', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_three_way_match_po_id'), ['po_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_three_way_match_status'), ['status'], unique=False)

    op.create_table('warehouse_inventory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.String(length=50), nullable=False),
    sa.Column('delivery_id', sa.String(length=50), nullable=False),
    sa.Column('item_code', sa.String(length=50), nullable=False),
    sa.Column('material_description', sa.Text(), nullable=False),
    sa.Column('material_category', sa.String(length=50), nullable=True),
    sa.Column('received_qty', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('storage_location_id', sa.String(length=100), nullable=True),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.Column('project_no', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('workflow_status', sa.Enum('warehouse', 'approved', 'rejected', name='workflowstatus'), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_id'], ['delivery.delivery_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('warehouse_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warehouse_inventory_company_name'), ['company_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouse_inventory_delivery_id'), ['delivery_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouse_inventory_item_code'), ['item_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouse_inventory_project_no'), ['project_no'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouse_inventory_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_warehouse_inventory_warehouse_id'), ['warehouse_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouse_inventory_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_warehouse_inventory_user_id'))
        batch_op.drop_index(batch_op.f('ix_warehouse_inventory_project_no'))
        batch_op.drop_index(batch_op.f('ix_warehouse_inventory_item_code'))
        batch_op.drop_index(batch_op.f('ix_warehouse_inventory_delivery_id'))
        batch_op.drop_index(batch_op.f('ix_warehouse_inventory_company_name'))

    op.drop_table('warehouse_inventory')
    with op.batch_alter_table('three_way_match', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_three_way_match_status'))
        batch_op.drop_index(batch_op.f('ix_three_way_match_po_id'))

    op.drop_table('three_way_match')
    with op.batch_alter_table('rfq_supplier', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rfq_supplier_total_score'))
        batch_op.drop_index(batch_op.f('ix_rfq_supplier_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_rfq_supplier_rfq_id'))

    op.drop_table('rfq_supplier')
    with op.batch_alter_table('bid', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bid_tender_id'))
        batch_op.drop_index(batch_op.f('ix_bid_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_bid_company_name'))

    op.drop_table('bid')
    with op.batch_alter_table('tender', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tender_tender_no'))
        batch_op.drop_index(batch_op.f('ix_tender_project_id'))
        batch_op.drop_index(batch_op.f('ix_tender_material_requisition_id'))
        batch_op.drop_index(batch_op.f('ix_tender_created_by'))
        batch_op.drop_index(batch_op.f('ix_tender_company_name'))

    op.drop_table('tender')
    with op.batch_alter_table('supplier_invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_invoice_po_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_invoice_invoice_no'))
        batch_op.drop_index(batch_op.f('ix_supplier_invoice_company_name'))

    op.drop_table('supplier_invoice')
    with op.batch_alter_table('rfq', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rfq_rfq_no'))
        batch_op.drop_index(batch_op.f('ix_rfq_mr_id'))
        batch_op.drop_index(batch_op.f('ix_rfq_company_name'))

    op.drop_table('rfq')
    with op.batch_alter_table('quality_control', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quality_control_user_id'))
        batch_op.drop_index(batch_op.f('ix_quality_control_order_id'))
        batch_op.drop_index(batch_op.f('ix_quality_control_company_name'))

    op.drop_table('quality_control')
    with op.batch_alter_table('purchase_order_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_item_purchase_order_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_item_material_requisition_id'))

    op.drop_table('purchase_order_item')
    with op.batch_alter_table('material_receipt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_receipt_receipt_no'))
        batch_op.drop_index(batch_op.f('ix_material_receipt_po_id'))
        batch_op.drop_index(batch_op.f('ix_material_receipt_company_name'))

    op.drop_table('material_receipt')
    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_user_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_order_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_delivery_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_company_name'))

    op.drop_table('delivery')
    with op.batch_alter_table('approval', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_requisition_id'))
        batch_op.drop_index(batch_op.f('ix_approval_company_name'))
        batch_op.drop_index(batch_op.f('ix_approval_approver_id'))

    op.drop_table('approval')
    with op.batch_alter_table('supplier_score', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_score_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_score_period'))
        batch_op.drop_index(batch_op.f('ix_supplier_score_overall_score'))
        batch_op.drop_index(batch_op.f('ix_supplier_score_company_name'))

    op.drop_table('supplier_score')
    with op.batch_alter_table('supplier_material', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_material_user_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_material_company_name'))

    op.drop_table('supplier_material')
    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_user_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_project_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_order_no'))
        batch_op.drop_index(batch_op.f('ix_purchase_order_company_name'))

    op.drop_table('purchase_order')
    with op.batch_alter_table('material_requisition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_requisition_user_id'))
        batch_op.drop_index(batch_op.f('ix_material_requisition_project_no'))
        batch_op.drop_index(batch_op.f('ix_material_requisition_project_id'))
        batch_op.drop_index(batch_op.f('ix_material_requisition_mr_no'))
        batch_op.drop_index(batch_op.f('ix_material_requisition_item_code'))
        batch_op.drop_index(batch_op.f('ix_material_requisition_company_name'))

    op.drop_table('material_requisition')
    with op.batch_alter_table('material_price_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_price_history_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_material_price_history_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_material_price_history_item_code'))
        batch_op.drop_index(batch_op.f('ix_material_price_history_company_name'))

    op.drop_table('material_price_history')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_project_id'))
        batch_op.drop_index(batch_op.f('ix_user_company_name'))
        batch_op.drop_index(batch_op.f('ix_user_company_email'))

    op.drop_table('user')
    with op.batch_alter_table('material_document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_document_trace_id'))
        batch_op.drop_index(batch_op.f('ix_material_document_company_name'))

    op.drop_table('material_document')
    with op.batch_alter_table('schedule_risk', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_risk_risk_score'))
        batch_op.drop_index(batch_op.f('ix_schedule_risk_project_no'))
        batch_op.drop_index(batch_op.f('ix_schedule_risk_item_code'))
        batch_op.drop_index(batch_op.f('ix_schedule_risk_company_name'))

    op.drop_table('schedule_risk')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_project_no'))
        batch_op.drop_index(batch_op.f('ix_project_company_name'))

    op.drop_table('project')
    with op.batch_alter_table('material_trace', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_trace_warehouse_id'))
        batch_op.drop_index(batch_op.f('ix_material_trace_trace_code'))
        batch_op.drop_index(batch_op.f('ix_material_trace_serial_no'))
        batch_op.drop_index(batch_op.f('ix_material_trace_project_no'))
        batch_op.drop_index(batch_op.f('ix_material_trace_po_no'))
        batch_op.drop_index(batch_op.f('ix_material_trace_lot_no'))
        batch_op.drop_index(batch_op.f('ix_material_trace_item_code'))
        batch_op.drop_index(batch_op.f('ix_material_trace_heat_no'))
        batch_op.drop_index(batch_op.f('ix_material_trace_delivery_id'))
        batch_op.drop_index(batch_op.f('ix_material_trace_company_name'))
        batch_op.drop_index(batch_op.f('ix_material_trace_batch_no'))

    op.drop_table('material_trace')
    with op.batch_alter_table('contact_inquiry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_inquiry_email'))

    op.drop_table('contact_inquiry')
    # ### end Alembic commands ###
