"""tenant-scoped document numbers and per-tenant sequences

Revision ID: 20260921_0002
Revises: 20260920_0001
Create Date: 2026-09-20 11:56:12.035196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260921_0002'
down_revision = '20260920_0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_sequence',
    sa.Column('key', sa.String(length=10), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('last_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('key', 'company_name')
    )
    with op.batch_alter_table('warehouse_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warehouse_inventory_warehouse_id'))
        batch_op.create_index(batch_op.f('ix_warehouse_inventory_warehouse_id'), ['warehouse_id'], unique=False)
        batch_op.create_unique_constraint('uq_wh_warehouse_id_company', ['warehouse_id', 'company_name'])
        batch_op.drop_constraint(batch_op.f('warehouse_inventory_delivery_id_fkey'), type_='foreignkey')

    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_delivery_id'))
        batch_op.create_index(batch_op.f('ix_delivery_delivery_id'), ['delivery_id'], unique=False)
        batch_op.create_unique_constraint('uq_delivery_id_company', ['delivery_id', 'company_name'])

    with op.batch_alter_table('material_receipt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_receipt_receipt_no'))
        batch_op.create_index(batch_op.f('ix_material_receipt_receipt_no'), ['receipt_no'], unique=False)
        batch_op.create_unique_constraint('uq_receipt_no_company', ['receipt_no', 'company_name'])

    with op.batch_alter_table('material_requisition', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_requisition_mr_no'))
        batch_op.create_index(batch_op.f('ix_material_requisition_mr_no'), ['mr_no'], unique=False)
        batch_op.create_unique_constraint('uq_mr_no_company', ['mr_no', 'company_name'])

    with op.batch_alter_table('material_trace', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_material_trace_trace_code'))
        batch_op.create_index(batch_op.f('ix_material_trace_trace_code'), ['trace_code'], unique=False)
        batch_op.create_unique_constraint('uq_trace_code_company', ['trace_code', 'company_name'])

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_project_no'))
        batch_op.create_index(batch_op.f('ix_project_project_no'), ['project_no'], unique=False)
        batch_op.create_unique_constraint('uq_project_no_company', ['project_no', 'company_name'])

    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_order_no'))
        batch_op.create_index(batch_op.f('ix_purchase_order_order_no'), ['order_no'], unique=False)
        batch_op.create_unique_constraint('uq_po_order_no_company', ['order_no', 'company_name'])

    with op.batch_alter_table('rfq', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rfq_rfq_no'))
        batch_op.create_index(batch_op.f('ix_rfq_rfq_no'), ['rfq_no'], unique=False)
        batch_op.create_unique_constraint('uq_rfq_no_company', ['rfq_no', 'company_name'])

    with op.batch_alter_table('supplier_invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_invoice_invoice_no'))
        batch_op.create_index(batch_op.f('ix_supplier_invoice_invoice_no'), ['invoice_no'], unique=False)
        batch_op.create_unique_constraint('uq_invoice_no_company', ['invoice_no', 'company_name'])

    with op.batch_alter_table('tender', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tender_tender_no'))
        batch_op.create_index(batch_op.f('ix_tender_tender_no'), ['tender_no'], unique=False)
        batch_op.create_unique_constraint('uq_tender_no_company', ['tender_no', 'company_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tender', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tender_no_company', type_='unique')
        batch_op.drop_index(batch_op.f('ix_tender_tender_no'))
        batch_op.create_index(batch_op.f('ix_tender_tender_no'), ['tender_no'], unique=True)

    with op.batch_alter_table('supplier_invoice', schema=None) as batch_op:
        batch_op.drop_constraint('uq_invoice_no_company', type_='unique')
        batch_op.drop_index(batch_op.f('ix_supplier_invoice_invoice_no'))
        batch_op.create_index(batch_op.f('ix_supplier_invoice_invoice_no'), ['invoice_no'], unique=True)

    with op.batch_alter_table('rfq', schema=None) as batch_op:
        batch_op.drop_constraint('uq_rfq_no_company', type_='unique')
        batch_op.drop_index(batch_op.f('ix_rfq_rfq_no'))
        batch_op.create_index(batch_op.f('ix_rfq_rfq_no'), ['rfq_no'], unique=True)

    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_constraint('uq_po_order_no_company', type_='unique')
        batch_op.drop_index(batch_op.f('ix_purchase_order_order_no'))
        batch_op.create_index(batch_op.f('ix_purchase_order_order_no'), ['order_no'], unique=True)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint('uq_project_no_company', type_='unique')
        batch_op.drop_index(batch_op.f('ix_project_project_no'))
        batch_op.create_index(batch_op.f('ix_project_project_no'), ['project_no'], unique=True)

    with op.batch_alter_table('material_trace', schema=None) as batch_op:
        batch_op.drop_constraint('uq_trace_code_company', type_='unique')
        batch_op.drop_index(batch_op.f('ix_material_trace_trace_code'))
        batch_op.create_index(batch_op.f('ix_material_trace_trace_code'), ['trace_code'], unique=True)

    with op.batch_alter_table('material_requisition', schema=None) as batch_op:
        batch_op.drop_constraint('uq_mr_no_company', type_='unique')
        batch_op.drop_index(batch_op.f('ix_material_requisition_mr_no'))
        batch_op.create_index(batch_op.f('ix_material_requisition_mr_no'), ['mr_no'], unique=True)

    with op.batch_alter_table('material_receipt', schema=None) as batch_op:
        batch_op.drop_constraint('uq_receipt_no_company', type_='unique')
        batch_op.drop_index(batch_op.f('ix_material_receipt_receipt_no'))
        batch_op.create_index(batch_op.f('ix_material_receipt_receipt_no'), ['receipt_no'], unique=True)

    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.drop_constraint('uq_delivery_id_company', type_='unique')
        batch_op.drop_index(batch_op.f('ix_delivery_delivery_id'))
        batch_op.create_index(batch_op.f('ix_delivery_delivery_id'), ['delivery_id'], unique=True)

    with op.batch_alter_table('warehouse_inventory', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('warehouse_inventory_delivery_id_fkey'), 'delivery', ['delivery_id'], ['delivery_id'])
        batch_op.drop_constraint('uq_wh_warehouse_id_company', type_='unique')
        batch_op.drop_index(batch_op.f('ix_warehouse_inventory_warehouse_id'))
        batch_op.create_index(batch_op.f('ix_warehouse_inventory_warehouse_id'), ['warehouse_id'], unique=True)

    op.drop_table('document_sequence')
    # ### end Alembic commands ###
