"""tenant-scoped document numbers and per-tenant sequences

Revision ID: 20260921_0002
Revises: 20260920_0001
Create Date: 2026-09-20 11:56:12.035196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20260921_0002'
down_revision = '20260920_0001'
branch_labels = None
depends_on = None


from sqlalchemy import inspect

def _ensure_document_sequence():
    bind = op.get_bind()
    if "document_sequence" not in inspect(bind).get_table_names():
        op.create_table(
            "document_sequence",
            sa.Column("key", sa.String(length=10), nullable=False),
            sa.Column("company_name", sa.String(length=100), nullable=False),
            sa.Column("last_value", sa.Integer(), nullable=False),
            sa.PrimaryKeyConstraint("key", "company_name"),
        )


def _ensure_tenant_unique(table_name, index_name, columns, constraint_name):
    bind = op.get_bind()
    inspector = inspect(bind)
    indexes = inspector.get_indexes(table_name)
    index_names = {item.get("name") for item in indexes}
    uniques = {item["name"] for item in inspector.get_unique_constraints(table_name)}
    if constraint_name not in uniques:
        op.create_unique_constraint(constraint_name, table_name, columns)
    # Existing deployments may already have an index with the legacy name.
    # The composite unique constraint above supplies the tenant-scoped lookup
    # index, so never recreate an index merely because its columns differ.
    if index_name not in index_names:
        op.create_index(index_name, table_name, columns, unique=False)


def upgrade():
    _ensure_document_sequence()
    bind = op.get_bind()
    inspector = inspect(bind)
    tables = set(inspector.get_table_names())
    targets = [
        ("warehouse_inventory", "ix_warehouse_inventory_warehouse_id", ["warehouse_id", "company_name"], "uq_wh_warehouse_id_company"),
        ("delivery", "ix_delivery_delivery_id", ["delivery_id", "company_name"], "uq_delivery_id_company"),
        ("material_receipt", "ix_material_receipt_receipt_no", ["receipt_no", "company_name"], "uq_receipt_no_company"),
        ("material_requisition", "ix_material_requisition_mr_no", ["mr_no", "company_name"], "uq_mr_no_company"),
        ("material_trace", "ix_material_trace_trace_code", ["trace_code", "company_name"], "uq_trace_code_company"),
        ("project", "ix_project_project_no", ["project_no", "company_name"], "uq_project_no_company"),
        ("purchase_order", "ix_purchase_order_order_no", ["order_no", "company_name"], "uq_po_order_no_company"),
        ("rfq", "ix_rfq_rfq_no", ["rfq_no", "company_name"], "uq_rfq_no_company"),
        ("supplier_invoice", "ix_supplier_invoice_invoice_no", ["invoice_no", "company_name"], "uq_invoice_no_company"),
        ("tender", "ix_tender_tender_no", ["tender_no", "company_name"], "uq_tender_no_company"),
    ]
    for table_name, index_name, columns, constraint_name in targets:
        if table_name in tables:
            _ensure_tenant_unique(table_name, index_name, columns, constraint_name)

    # This migration intentionally removes the legacy delivery FK.
    if "warehouse_inventory" in tables:
        fks = {fk["name"] for fk in inspector.get_foreign_keys("warehouse_inventory")}
        if "warehouse_inventory_delivery_id_fkey" in fks:
            with op.batch_alter_table("warehouse_inventory", schema=None) as batch_op:
                batch_op.drop_constraint("warehouse_inventory_delivery_id_fkey", type_="foreignkey")

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tender', schema=None) as batch_op:
        batch_op.drop_constraint('uq_tender_no_company', type_='unique')
        batch_op.drop_index(batch_op.f('ix_tender_tender_no'))
        batch_op.create_index(batch_op.f('ix_tender_tender_no'), ['tender_no'], unique=True)

    with op.batch_alter_table('supplier_invoice', schema=None) as batch_op:
        batch_op.drop_constraint('uq_invoice_no_company', type_='unique')
        batch_op.drop_index(batch_op.f('ix_supplier_invoice_invoice_no'))
        batch_op.create_index(batch_op.f('ix_supplier_invoice_invoice_no'), ['invoice_no'], unique=True)

    with op.batch_alter_table('rfq', schema=None) as batch_op:
        batch_op.drop_constraint('uq_rfq_no_company', type_='unique')
        batch_op.drop_index(batch_op.f('ix_rfq_rfq_no'))
        batch_op.create_index(batch_op.f('ix_rfq_rfq_no'), ['rfq_no'], unique=True)

    with op.batch_alter_table('purchase_order', schema=None) as batch_op:
        batch_op.drop_constraint('uq_po_order_no_company', type_='unique')
        batch_op.drop_index(batch_op.f('ix_purchase_order_order_no'))
        batch_op.create_index(batch_op.f('ix_purchase_order_order_no'), ['order_no'], unique=True)

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint('uq_project_no_company', type_='unique')
        batch_op.drop_index(batch_op.f('ix_project_project_no'))
        batch_op.create_index(batch_op.f('ix_project_project_no'), ['project_no'], unique=True)

    with op.batch_alter_table('material_trace', schema=None) as batch_op:
        batch_op.drop_constraint('uq_trace_code_company', type_='unique')
        batch_op.drop_index(batch_op.f('ix_material_trace_trace_code'))
        batch_op.create_index(batch_op.f('ix_material_trace_trace_code'), ['trace_code'], unique=True)

    with op.batch_alter_table('material_requisition', schema=None) as batch_op:
        batch_op.drop_constraint('uq_mr_no_company', type_='unique')
        batch_op.drop_index(batch_op.f('ix_material_requisition_mr_no'))
        batch_op.create_index(batch_op.f('ix_material_requisition_mr_no'), ['mr_no'], unique=True)

    with op.batch_alter_table('material_receipt', schema=None) as batch_op:
        batch_op.drop_constraint('uq_receipt_no_company', type_='unique')
        batch_op.drop_index(batch_op.f('ix_material_receipt_receipt_no'))
        batch_op.create_index(batch_op.f('ix_material_receipt_receipt_no'), ['receipt_no'], unique=True)

    with op.batch_alter_table('delivery', schema=None) as batch_op:
        batch_op.drop_constraint('uq_delivery_id_company', type_='unique')
        batch_op.drop_index(batch_op.f('ix_delivery_delivery_id'))
        batch_op.create_index(batch_op.f('ix_delivery_delivery_id'), ['delivery_id'], unique=True)

    with op.batch_alter_table('warehouse_inventory', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('warehouse_inventory_delivery_id_fkey'), 'delivery', ['delivery_id'], ['delivery_id'])
        batch_op.drop_constraint('uq_wh_warehouse_id_company', type_='unique')
        batch_op.drop_index(batch_op.f('ix_warehouse_inventory_warehouse_id'))
        batch_op.create_index(batch_op.f('ix_warehouse_inventory_warehouse_id'), ['warehouse_id'], unique=True)

    op.drop_table('document_sequence')
    # ### end Alembic commands ###
